### ISSUE TITLE
Video recording crashes

### ISSUE THREAD

**Issue by eastskykang** [leggedrobotics/raisimOgre#10] opened 2019-10-05 15:41 UTC
current ffmpeg argument is as follows

```cpp
std::string command =
      "ffmpeg -r " + std::to_string(desiredFPS_) + " -f rawvideo -pix_fmt rgb24 -s " + std::to_string(w) + "x"
          + std::to_string(h) +
          " -i - -threads 0 -preset fast -y -pix_fmt yuv420p -crf 21 " + currentVideoFile_;
```

this settings crashes the application on my machine. 

```cpp
std::string command =
      "ffmpeg -r " + std::to_string(desiredFPS_) + " -f rawvideo -pix_fmt rgb24 -s " + std::to_string(w) + "x"
          + std::to_string(h) +
          " -i - -threads 0 -preset fast -y -pix_fmt yuv420p -crf 21 " + currentVideoFile_;
```

it seems that ```-pix_fmt yuv420p``` option makes a problem. Without this option, the recording works fine.

**Comment by jhwangbo** [comment] 2019-10-12 07:55
The issue is resolved in 299461dd3ed378d41b9848441f28f29347609e61

**Closed as completed by jhwangbo** 2019-10-12 07:55 UTC
